# Env vars passate al systemd --user (lette al login).
# Forzano Wayland nativo dove possibile + propagano dark mode a Qt apps.
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=gtk3
SDL_VIDEODRIVER=wayland
_JAVA_AWT_WM_NONREPARENTING=1
